name: Lint, Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: |
          npm run lint:css
          npm run lint:ts

      - name: Build
        run: |
          npm run build
          cp README.md dist
          cp LICENSE dist
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_lint
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Set Git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Deploy to main
        run: |
          git checkout main || git checkout -b main
          find -not \( -path ./.git -prune \) -not \( -path ./dist -prune \) -exec git rm -rf {} + 
          cp -r dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy website"
          git push -f origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
